FROM debian:stable-slim

# ###license-information-start###
# The MOSAIC-Project - Debian Stable
# __
# Copyright (C) 2009 - 2026 Institute for Community Medicine
# University Medicine of Greifswald - kontakt-ths@med.uni-greifswald.de
# __
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ###license-information-end###

# variables
ARG DATE_YMD="20260304"
ARG WAIT_FOR_IT_FILE="wait-for-it.sh"
ARG WAIT_FOR_IT_DOWNLOAD_URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/ed77b63706ea721766a62ff22d3a251d8b4a6a30/${WAIT_FOR_IT_FILE}"
ARG WAIT_FOR_IT_SHA256="2ea7475e07674e4f6c1093b4ad6b0d8cbbc6f9c65c73902fb70861aa66a6fbc0"

ENV HOME="/opt/mosaic" \
    USER="mosaic" \
    \
    MOSAIC_UID="1111" \
    MOSAIC_GID="1111" \
    MOS_READY_PATH="/opt/mosaic/ready" \
    MOS_TEMP_PATH="/opt/mosaic/temp" \
    TZ="Europe/Berlin" \
    MOS_RUN_MODE="service" \
    ENTRY_LOGS="/entrypoint-logs" \
    ENTRY_USAGE="/entrypoint-help-and-usage"

# annotations
LABEL org.opencontainers.image.authors="ronny.schuldt@uni-greifswald.de" \
      org.opencontainers.image.source="https://hub.docker.com/repository/docker/mosaicgreifswald/debian" \
      org.opencontainers.image.version="${DATE_YMD}" \
      org.opencontainers.image.vendor="uni-greifswald.de" \
      org.opencontainers.image.title="mosaic-debian" \
      org.opencontainers.image.license="AGPLv3"

COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${HOME}"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["help-and-usage", "${ENTRY_USAGE}"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["README.md", "${ENTRY_USAGE}/layer-readme/README-debian.md"]
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
	--mount=type=cache,target=/downloads,sharing=locked,id=downloads \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo -n "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
    echo ", downloads ($(du -sh /downloads/ | awk '{print $1}'), $(ls /downloads | wc -w) files)" && \
    cd ${HOME} && \
    echo "> 1. install system-updates" && \
    apt-get update && apt-get upgrade -y && \
    \
    echo "> 2. install missing packages (curl,procps) " && \
    apt-get install -y curl procps && \
    \
    echo "> 3. create user and group" && \
    groupadd --g ${MOSAIC_GID} ${USER} && \
    useradd --no-log-init -m -u ${MOSAIC_UID} -g ${MOSAIC_GID} -d ${HOME} ${USER} && \
    \
    echo "> 4. create folders and permissions" && \
    mkdir -m 777 ${MOS_READY_PATH} ${MOS_TEMP_PATH} ${ENTRY_LOGS} && \
    \
    echo -n "> 5. download wait-for-it-script" && \
    cd /downloads && \
	((test -f ${WAIT_FOR_IT_FILE} && echo e) || (echo d && curl -LfsSO ${WAIT_FOR_IT_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${WAIT_FOR_IT_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${WAIT_FOR_IT_FILE} | grep -q ${WAIT_FOR_IT_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${WAIT_FOR_IT_FILE})" && exit 1) && \
    cp ${WAIT_FOR_IT_FILE} ${HOME}/${WAIT_FOR_IT_FILE} && \
    cd ${HOME} && \
    \
    echo "> 6. register bash-scripts" && \
    ln -s ${HOME}/register.sh /usr/bin/register && \
    ln -s ${HOME}/versions.sh /usr/bin/versions && \
    ln -s ${HOME}/entrypoints.sh /usr/bin/entrypoints && \
    ln -s ${HOME}/help.sh /usr/bin/help && \
    ln -s ${HOME}/envs.sh /usr/bin/envs && \
    ln -s ${HOME}/processes.sh /usr/bin/processes && \
    ln -s ${HOME}/examples.sh /usr/bin/examples && \
    ln -s ${HOME}/wait-for-it.sh /usr/bin/wait-for-it && \
    \
    echo "> 7. register versions and entrypoints" && \
    /bin/bash ${HOME}/register.sh \
      --add-version="Architecture:$(uname -m)" \
      --add-version='Distribution:$(. /etc/os-release && echo "$NAME $DEBIAN_VERSION_FULL ($VERSION_CODENAME)")' \
      --add-entrypoint="ENTRY_LOGS:${ENTRY_LOGS}" && \
    \
    echo "> 8. cleanup" && \
    apt-get autoremove -y && \
    chown ${USER}:${USER} -R ${HOME} ${MOS_READY_PATH} ${MOS_TEMP_PATH} ${ENTRY_LOGS} ${ENTRY_USAGE} && \
    chmod 777 -R ${HOME} && chmod 444 -R ${HOME}/*.txt && \
    rm -rf install.log

WORKDIR ${HOME}
USER ${USER}

HEALTHCHECK CMD ["./healthcheck.sh"]
CMD ["./run.sh"]
