services:

  mysql:
    image: mosaicgreifswald/mysql
    ports:
      - 3306:3306
    environment:
      TTP_MYSQL_ROOT_PASSWORD: top-secret
    volumes:
      - ./db-data:/entrypoint-mysql-data
      - ./sqls:/entrypoint-mysql-sqls
      - ./my.cnf:/entrypoint-mysql-my-cnf
      - ./logs:/entrypoint-mysql-logs