ARG TAG=mosaicgreifswald/debian:latest
FROM ${TAG} AS build

# ###license-information-start###
# The MOSAIC-Project - MySQL-Server
# __
# Copyright (C) 2009 - 2026 Institute for Community Medicine
# University Medicine of Greifswald - kontakt-ths@med.uni-greifswald.de
# __
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ###license-information-end###

# variables
ARG MYSQL_VERSION="8.4.9"
ARG MYSQL_DOWNLOAD_URL="https://cdn.mysql.com/Downloads/MySQL-8.4"
ARG MYSQL_X86_64_FILE="mysql-${MYSQL_VERSION}-linux-glibc2.28-x86_64-minimal.tar.xz"
ARG MYSQL_X86_64_SHA256="d0142fc30e04bae7f15a46567238adf8956acccd35c5bca6e448322644536e3d"
ARG MYSQL_AARCH64_FILE="mysql-${MYSQL_VERSION}-linux-glibc2.28-aarch64.tar.xz"
ARG MYSQL_AARCH64_SHA256="497a4143d542b5b85ec7249016b0ff6ac6e7a855302a9822f667ca293d801aea"

ENV MYSQL_HOME="${HOME}/mysql"

# create image
USER root
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${MOS_TEMP_PATH}"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["help-and-usage", "/help-and-usage/"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["README.md", "/help-and-usage/layer-readme/README-mysql.md"]
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
    --mount=type=cache,target=/downloads,sharing=locked,id=downloads \
	echo -n "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
	echo ", downloads ($(du -sh /downloads/ | awk '{print $1}'), $(ls /downloads | wc -w) files)" && \
    \
    echo "> 1. install system-updates" && \
    apt-get update && apt-get upgrade -y && \
    \
    echo "> 2. install xz-utils" && \
    apt-get install -y xz-utils && \
    \
    echo -n "> 3. mysql-server " && \
	cd /downloads && \
    ARCH="$([ "$(uname -m)" = "x86_64" ] && echo "x86_64" || echo "aarch64")" && \
    MYSQL_FILE="$([ "${ARCH}" = "x86_64" ] && echo "${MYSQL_X86_64_FILE}" || echo "${MYSQL_AARCH64_FILE}")" && \
    MYSQL_SHA256="$([ "${ARCH}" = "x86_64" ] && echo "${MYSQL_X86_64_SHA256}" || echo "${MYSQL_AARCH64_SHA256}")" && \
    ((test -f ${MYSQL_FILE} && echo e) || (echo d && curl -LfsSO ${MYSQL_DOWNLOAD_URL}/${MYSQL_FILE}) || (>&2 echo -e "\ncurl -LfsSO ${MYSQL_DOWNLOAD_URL}/${MYSQL_FILE}\n" && exit 1)) && \
    (sha256sum ${MYSQL_FILE} | grep ${MYSQL_SHA256} > /dev/null || (>&2 echo "sha256sum(${ARCH}) failed $(sha256sum ${MYSQL_FILE})" && exit 1)) && \
    tar xf ${MYSQL_FILE} && \
    mv $(ls --color=never -d mysql*/ | sed -e 's-/$--') ${MYSQL_HOME} && \
    mv -t ${MYSQL_HOME}/ ${MOS_TEMP_PATH}/*.sh ${MOS_TEMP_PATH}/*.cnf && \
    echo "export LD_LIBRARY_PATH=/opt/mysql/lib:/lib:/lib64:/usr/lib" > ${MYSQL_HOME}/library_path.sh

###########
FROM ${TAG}

ARG DATE_YMD="20260304"
ENV MYSQL_HOME="${HOME}/mysql" \
    MYSQL_OPTS="" \
    MYSQL_ENABLE_UPDATE_SCANNER="false" \
    MYSQL_LOG_TO="CONSOLE" \
    \
    ENTRY_MYSQL_DATADIR="/entrypoint-mysql-data" \
    ENTRY_MYSQL_SQLS="/entrypoint-mysql-sqls" \
    ENTRY_MYSQL_UPDATE_SQLS="/entrypoint-mysql-update-sqls" \
    ENTRY_MYSQL_MY_CNF="/entrypoint-mysql-my-cnf" \
    ENTRY_MYSQL_SOCKET="/entrypoint-mysql-socket" \
    ENTRY_MYSQL_LOGS="/entrypoint-mysql-logs"

# annotations
LABEL org.opencontainers.image.authors="ronny.schuldt@uni-greifswald.de" \
      org.opencontainers.image.source="https://hub.docker.com/repository/docker/mosaicgreifswald/mysql" \
      org.opencontainers.image.version="8-${DATE_YMD}" \
      org.opencontainers.image.vendor="uni-greifswald.de" \
      org.opencontainers.image.title="mosaic-mysql" \
      org.opencontainers.image.license="AGPLv3"

# create image
USER root
COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["${MYSQL_HOME}", "${MYSQL_HOME}"]
COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["/help-and-usage", "${ENTRY_USAGE}/"]

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
    echo "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
	\
    echo "> 1. install system-updates" && \
    apt-get update && apt-get upgrade -y && \
    \
    echo "> 2. install procps and libraries" && \
    apt-get install -y procps libaio1t64 libnuma1 libncurses6 && \
    mkdir -m 777 ${ENTRY_MYSQL_DATADIR} ${ENTRY_MYSQL_SQLS} ${ENTRY_MYSQL_UPDATE_SQLS} ${ENTRY_MYSQL_SOCKET} ${ENTRY_LOGS}/mysql && \
    echo "export PATH=${MYSQL_HOME}/bin:${PATH}" > /etc/profile.d/mysql.sh && \
    \
    echo "> 3. register mysql" && \
    register \
        --add-version="MySQL-Server:\$(${MYSQL_HOME}/bin/mysqld -V 2>/dev/null | sed -r 's/^.+Ver ([0-9\.]+) .+$/\1/' | cat)" \
        --add-entrypoint="ENTRY_MYSQL_DATADIR:${ENTRY_MYSQL_DATADIR}" \
        --add-entrypoint="ENTRY_MYSQL_SQLS:${ENTRY_MYSQL_SQLS}" \
        --add-entrypoint="ENTRY_MYSQL_UPDATE_SQLS:${ENTRY_MYSQL_UPDATE_SQLS}" \
        --add-entrypoint="ENTRY_MYSQL_MY_CNF:${ENTRY_MYSQL_MY_CNF}" \
        --add-entrypoint="ENTRY_MYSQL_SOCKET:${ENTRY_MYSQL_SOCKET}" \
        --add-entrypoint="ENTRY_MYSQL_LOGS:${ENTRY_MYSQL_LOGS}" \
        --add-healthcheck-script="${MYSQL_HOME}/healthcheck_mysql.sh" \
        --add-process="mysql:10:service:${MYSQL_HOME}/run_mysql.sh:${MYSQL_HOME}/mysql_started.sh" && \
    \
    echo "> 4. cleanup" && \
    apt-get autoremove -y && \
    ln -s ${MYSQL_HOME}/my.cnf ${ENTRY_MYSQL_MY_CNF} && \
    ln -s ${ENTRY_LOGS}/mysql ${ENTRY_MYSQL_LOGS} && \
    ln -s ${MYSQL_HOME}/bin/* /usr/bin/ && \
    ln -s /dev/stdout ${MYSQL_HOME}/stdout.log && \
    ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/libaio.so.1 && \
    chown ${USER}:${USER} -R ${MYSQL_HOME} ${ENTRY_MYSQL_DATADIR} ${ENTRY_MYSQL_SQLS} ${ENTRY_MYSQL_UPDATE_SQLS} \
    	${ENTRY_MYSQL_SOCKET} ${ENTRY_MYSQL_MY_CNF} ${ENTRY_MYSQL_LOGS} ${ENTRY_USAGE} && \
    chmod 777 ${MYSQL_HOME} && chmod 666 ${MYSQL_HOME}/my.cnf

USER ${USER}

# ports
EXPOSE 3306
