services:
  wildfly:
    image: mosaicgreifswald/wildfly
    environment:
      WF_ADMIN_USER: top-member
      WF_ADMIN_PASS: top-secret
  jmeter:
    image: mosaicgreifswald/jmeter
    depends_on:
      - wildfly
    env_file:
      - envs/jmeter.env
    environment:
      MOS_WAIT_FOR_PORTS: wildfly:9990
    volumes:
      - ./jmeter-tests:/entrypoint-jmeter-testfiles
      - ./jmeter-props:/entrypoint-jmeter-properties
      - ./logs:/entrypoint-jmeter-logs
