ARG TAG=mosaicgreifswald/zulujre:21
FROM ${TAG} AS build

# ###license-information-start###
# The MOSAIC-Project - WildFly with MySQL-Connector and Healthcheck
# __
# Copyright (C) 2009 - 2026 Institute for Community Medicine
# University Medicine of Greifswald - mosaic-project@uni-greifswald.de
# __
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ###license-information-end###

# variables
ARG MAVEN_REPOSITORY="https://repo1.maven.org/maven2"

ARG WILDFLY_VERSION="38.0.1.Final"
ARG WILDFLY_FILE="wildfly-${WILDFLY_VERSION}.tar.gz"
ARG WILDFLY_DOWNLOAD_URL="https://github.com/wildfly/wildfly/releases/download/${WILDFLY_VERSION}/${WILDFLY_FILE}"
ARG WILDFLY_SHA256="35bac69f742054734cc05263642adfc4e2073211ef635e9e8c812c6de6c3a907"

ARG MYSQL_CONNECTOR_VERSION="9.6.0"
ARG MYSQL_CONNECTOR_FILE="mysql-connector-j-${MYSQL_CONNECTOR_VERSION}.jar"
ARG MYSQL_CONNECTOR_DOWNLOAD_URL="${MAVEN_REPOSITORY}/com/mysql/mysql-connector-j/${MYSQL_CONNECTOR_VERSION}/${MYSQL_CONNECTOR_FILE}"
ARG MYSQL_CONNECTOR_SHA256="66df1d453789dc8cb759a7dc17f58646893bf28483f262328650f170472a6ead"

ARG MARIA_CONNECTOR_VERSION="3.5.7"
ARG MARIA_CONNECTOR_FILE="mariadb-java-client-${MARIA_CONNECTOR_VERSION}.jar"
ARG MARIA_CONNECTOR_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/mariadb/jdbc/mariadb-java-client/${MARIA_CONNECTOR_VERSION}/${MARIA_CONNECTOR_FILE}"
ARG MARIA_CONNECTOR_SHA256="07bb1229dc184f3313a5aef4c5a6b3207c8dbaa09db4a26814c936f004b4c526"

ARG PSQL_CONNECTOR_VERSION="42.7.10"
ARG PSQL_CONNECTOR_FILE="postgresql-${PSQL_CONNECTOR_VERSION}.jar"
ARG PSQL_CONNECTOR_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/postgresql/postgresql/${PSQL_CONNECTOR_VERSION}/${PSQL_CONNECTOR_FILE}"
ARG PSQL_CONNECTOR_SHA256="cab1cd67cfa25c25de4348e532298028288a877ba01c77d1619fe45416193387"

ARG ECLIPSELINK_VERSION="4.0.9"
ARG ECLIPSELINK_FILE="eclipselink-${ECLIPSELINK_VERSION}.jar"
ARG ECLIPSELINK_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/eclipse/persistence/eclipselink/${ECLIPSELINK_VERSION}/${ECLIPSELINK_FILE}"
ARG ECLIPSELINK_SHA256="42eec9b7b9e3dd7cbfec9ecfab8f682dd0826cc6b10dae238d88c3c7ebc3d60e"
ARG ECLIPSEJSON_FILE="org.eclipse.persistence.json-${ECLIPSELINK_VERSION}.jar"
ARG ECLIPSEJSON_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/eclipse/persistence/org.eclipse.persistence.json/${ECLIPSELINK_VERSION}/${ECLIPSEJSON_FILE}"
ARG ECLIPSEJSON_SHA256="dfc9da258163e8ff52c42255857e499bc5f84a99852c4290a095da75420e824c"
ARG ECLIPSECORE_FILE="org.eclipse.persistence.core-${ECLIPSELINK_VERSION}.jar"
ARG ECLIPSECORE_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/eclipse/persistence/org.eclipse.persistence.core/${ECLIPSELINK_VERSION}/${ECLIPSECORE_FILE}"
ARG ECLIPSECORE_SHA256="2996192736c100ab2e2f90d8589cbf1c87b41317dd93f037c0e760ccd8a66e33"

ENV WILDFLY_HOME="${HOME}/wildfly" \
    JBOSS_CLI="${HOME}/wildfly/bin/jboss-cli.sh" \
    ENTRY_WILDFLY_DEPLOYS="/entrypoint-wildfly-deployments"

USER root
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${MOS_TEMP_PATH}"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["help-and-usage", "/help-and-usage"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["README.md", "/help-and-usage/layer-readme/README-wildfly.md"]
RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 1. get mysql-connector " && \
	((test -f ${MYSQL_CONNECTOR_FILE} && echo e) || (echo d && curl -LfsSO ${MYSQL_CONNECTOR_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${MYSQL_CONNECTOR_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${MYSQL_CONNECTOR_FILE} | grep -q ${MYSQL_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${MYSQL_CONNECTOR_FILE})" && exit 1)

RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 2. get mariadb-connector " && \
	((test -f ${MARIA_CONNECTOR_FILE} && echo e) || (echo d && curl -LfsSO ${MARIA_CONNECTOR_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${MARIA_CONNECTOR_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${MARIA_CONNECTOR_FILE} | grep -q ${MARIA_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${MARIA_CONNECTOR_FILE})" && exit 1)

RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 3. get postgresql-connector " && \
    ((test -f ${PSQL_CONNECTOR_FILE} && echo e) || (echo d && curl -LfsSO ${PSQL_CONNECTOR_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${PSQL_CONNECTOR_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${PSQL_CONNECTOR_FILE} | grep -q ${PSQL_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${PSQL_CONNECTOR_FILE})" && exit 1)

RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 4. get eclipselink " && \
    ((test -f ${ECLIPSELINK_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSELINK_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSELINK_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${ECLIPSELINK_FILE} | grep -q ${ECLIPSELINK_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSELINK_FILE})" && exit 1)

RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 5. get eclipse.persistence.json " && \
    ((test -f ${ECLIPSEJSON_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSEJSON_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSEJSON_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${ECLIPSEJSON_FILE} | grep -q ${ECLIPSEJSON_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSEJSON_FILE})" && exit 1)

RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 6. get eclipse.persistence.core " && \
	((test -f ${ECLIPSECORE_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSECORE_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSECORE_DOWNLOAD_URL} \n" && exit 1)) && \
	sha256sum ${ECLIPSECORE_FILE} | grep -q ${ECLIPSECORE_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSECORE_FILE})" && exit 1)

RUN cd ${MOS_TEMP_PATH} && \
    echo -n "> 7. install wildfly " && \
	((test -f ${WILDFLY_FILE} && echo e) || (echo d && curl -LfsSO ${WILDFLY_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${WILDFLY_DOWNLOAD_URL} \n" && exit 1)) && \
	(sha256sum ${WILDFLY_FILE} | grep -q ${WILDFLY_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${WILDFLY_FILE})" && exit 1)) && \
	tar xf ${WILDFLY_FILE} && \
	mv wildfly-${WILDFLY_VERSION} ${WILDFLY_HOME} && \
    mv -t ${WILDFLY_HOME}/ ./*.sh ./internal_cli && \
	#rm -rf ${WILDFLY_HOME}/bin/*.bat ${WILDFLY_HOME}/bin/*.ps1 ${WILDFLY_HOME}/docs && \
	mkdir -pm 777 ${WILDFLY_HOME}/standalone/log && touch ${WILDFLY_HOME}/standalone/log/server.log

RUN echo "> 8. start wildfly" && \
    (${WILDFLY_HOME}/bin/standalone.sh &) && \
    START=$(date +%s) && \
    TIMEOUT=120 && \
    (until `/bin/bash ${WILDFLY_HOME}/wildfly_started.sh`;do sleep 1;SEC=$(($(date +%s)-START));if [ ${SEC} -ge $TIMEOUT ];then >&2 echo "starting-timeout (TIMEOUT=${TIMEOUT})";exit 1;fi;done) && \
    echo "> 9. prepare wildfly" && \
    ($JBOSS_CLI --connect --commands=" \
        module add --name=clients.mysql --resources=${MOS_TEMP_PATH}/${MYSQL_CONNECTOR_FILE} --dependencies=javax.api\,javax.transaction.api, \
        /subsystem=datasources/jdbc-driver=mysql:add(driver-module-name=clients.mysql,driver-class-name=com.mysql.cj.jdbc.Driver), \
        module add --name=clients.mariadb --resources=${MOS_TEMP_PATH}/${MARIA_CONNECTOR_FILE} --dependencies=javax.api\,javax.transaction.api, \
        /subsystem=datasources/jdbc-driver=mariadb:add(driver-module-name=clients.mariadb,driver-class-name=org.mariadb.jdbc.Driver), \
        module add --name=clients.postgresql --resources=${MOS_TEMP_PATH}/${PSQL_CONNECTOR_FILE} --dependencies=javax.api\,javax.transaction.api, \
        /subsystem=datasources/jdbc-driver=postgresql:add(driver-module-name=clients.postgresql,driver-class-name=org.postgresql.Driver), \
        module add --name=org.eclipse.persistence --resources=${MOS_TEMP_PATH}/${ECLIPSELINK_FILE} --dependencies=java.logging\,java.management\,java.naming\,jakarta.annotation.api\,jakarta.enterprise.api\,jakarta.json.api\,jakarta.persistence.api\,jakarta.transaction.api\,jakarta.validation.api\,jakarta.xml.bind.api\,org.antlr\,org.jboss.as.jpa.spi\,org.jboss.logging\,org.jboss.vfs\,java.rmi\,java.desktop\,javax.api\,org.eclipse.persistence.json, \
        module add --name=org.eclipse.persistence.json --resources=${MOS_TEMP_PATH}/${ECLIPSEJSON_FILE} --dependencies=org.eclipse.persistence.core, \
        module add --name=org.eclipse.persistence.core --resources=${MOS_TEMP_PATH}/${ECLIPSECORE_FILE}, \
        module remove --name=system.layers.base.org.eclipse.persistence, \
        /extension=org.wildfly.extension.microprofile.health-smallrye:add, \
        /subsystem=microprofile-health-smallrye:add, \
        /subsystem=undertow/server=default-server/ajp-listener=myListener:add(socket-binding=ajp, scheme=http), \
        /subsystem=elytron/file-audit-log=local-audit:remove(), \
        /subsystem=logging/pattern-formatter=DATE_DETAILED:add(pattern=\"%d %-5p %-4L [%c] (%t) %s%E%n\"), \
        /subsystem=logging/pattern-formatter=DATE_COMPACT:add(pattern=\"%d %-5.5p %-4.4L %-40.40c{2.} | %m%n\"), \
        /subsystem=logging/pattern-formatter=NO_DATE_DETAILED:add(pattern=\"%d{HH:mm:ss,SSS} %-5p %-4L [%c] (%t) %s%E%n\"), \
        /subsystem=logging/pattern-formatter=NO_DATE_COMPACT:add(pattern=\"%d{HH:mm:ss,SSS} %-5.5p %-4.4L %-40.40c{2.} | %m%n\")" || exit 1) && \
    cp ${WILDFLY_HOME}/standalone/configuration/standalone.xml ${WILDFLY_HOME}/standalone/configuration/standalone_xml_history/standalone.${USER}.xml && \
    ($JBOSS_CLI --connect --commands=" \
        /subsystem=deployment-scanner/scanner=default:write-attribute(name=scan-enabled,value=false), \
        /subsystem=deployment-scanner/scanner=entrypoint:add(scan-interval=5000,path=${ENTRY_WILDFLY_DEPLOYS}), \
        :shutdown" || exit 1)

RUN echo "> 10. register versions" && \
	register \
      --add-version="WildFly:${WILDFLY_VERSION}" \
      --add-version="MySQL-Connector:${MYSQL_CONNECTOR_VERSION}" \
      --add-version="MariaDB-Connector:${MARIA_CONNECTOR_VERSION}" \
      --add-version="PostgreSQL-Connector:${PSQL_CONNECTOR_VERSION}" \
      --add-version="EclipseLink:${ECLIPSELINK_VERSION}"

RUN echo "> 11. cleanup" && \
    mkdir -pm 777 ${WILDFLY_HOME}/standalone/data/addins && \
    chmod 777 -R ${WILDFLY_HOME}/domain/configuration && \
    rm -rf ${WILDFLY_HOME}/standalone/configuration/standalone_xml_history/current/* ${WILDFLY_HOME}/standalone/log/*

###########
FROM ${TAG}

ARG DATE_YMD="20260304"
ENV WILDFLY_HOME="${HOME}/wildfly" \
    JBOSS_CLI="${HOME}/wildfly/bin/jboss-cli.sh" \
    LAUNCH_JBOSS_IN_BACKGROUND="true" \
    LOG4J_FORMAT_MSG_NO_LOOKUPS="true" \
    \
    ENTRY_WILDFLY_CLI="/entrypoint-wildfly-cli" \
    ENTRY_WILDFLY_DEPLOYS="/entrypoint-wildfly-deployments" \
    ENTRY_WILDFLY_ADDINS="/entrypoint-wildfly-addins" \
	ENTRY_WILDFLY_LOGS="/entrypoint-wildfly-logs" \
	ENTRY_WILDFLY_SERVER_KEYSTORE="/entrypoint-wildfly-server-keystore" \
	\
    WF_MARKERFILES="auto" \
    WF_ADMIN_USER="admin" \
    WF_DEBUG="false" \
    DEBUG_PORT="*:8787" \
    JAVA_OPTS="-server -Xms1G -Xmx6G -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman" \
	WF_MAX_PARAMETERS="100000" \
	WF_ENABLE_HTTP2="FALSE"

# annotations
LABEL org.opencontainers.image.authors="ronny.schuldt@uni-greifswald.de" \
      org.opencontainers.image.source="https://hub.docker.com/repository/docker/mosaicgreifswald/wildfly" \
      org.opencontainers.image.version="38-${DATE_YMD}" \
      org.opencontainers.image.vendor="uni-greifswald.de" \
      org.opencontainers.image.title="mosaic-wildfly" \
      org.opencontainers.image.license="AGPLv3" \
      org.opencontainers.image.description="This is a Docker image for the Java application server WildFly. The image is based on slim debian-image and prepared for the tools of the university medicine greifswald (but can also be used for other similar projects)."

# create folders and permissions
USER root
COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["${WILDFLY_HOME}", "${WILDFLY_HOME}"]
COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["${HOME}/versions.sh", "${HOME}"]
COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["/help-and-usage", "${ENTRY_USAGE}/"]
RUN cd ${MOS_TEMP_PATH} && \
    echo "> 1. install system-updates" && \
    if [ "$(date +%F)" != "$(stat -c '%.10y' $(ls -t /var/lib/dpkg/info/*.list | head -n 1))" ]; then \
		apt-get update && apt-get upgrade -y; \
	fi && \
    \
    echo "> 2. create folders and permissions" && \
    mkdir -m 777 ${ENTRY_WILDFLY_CLI} ${ENTRY_WILDFLY_DEPLOYS} ${ENTRY_LOGS}/wildfly && \
    chown ${USER}:${USER} -R ${ENTRY_WILDFLY_CLI} ${ENTRY_WILDFLY_DEPLOYS} ${ENTRY_LOGS}/wildfly && \
    ln -s ${ENTRY_LOGS}/wildfly ${ENTRY_WILDFLY_LOGS} && \
    echo -n "true" > ${MOS_READY_PATH}/markerfiles_mode && \
    \
    echo "> 3. register wildfly" && \
    register \
      --add-entrypoint="ENTRY_WILDFLY_CLI:${ENTRY_WILDFLY_CLI}" \
      --add-entrypoint="ENTRY_WILDFLY_DEPLOYS:${ENTRY_WILDFLY_DEPLOYS}" \
      --add-entrypoint="ENTRY_WILDFLY_ADDINS:${ENTRY_WILDFLY_ADDINS}" \
      --add-entrypoint="ENTRY_WILDFLY_LOGS:${ENTRY_WILDFLY_LOGS}" \
      --add-entrypoint="ENTRY_WILDFLY_SERVER_KEYSTORE:${ENTRY_WILDFLY_SERVER_KEYSTORE}" \
      --add-healthcheck-script="${WILDFLY_HOME}/healthcheck_wildfly.sh" \
      --add-process="wildfly:20:service:${WILDFLY_HOME}/run_wildfly.sh:${WILDFLY_HOME}/wildfly_started.sh" && \
    \
    echo "> 4. cleanup" && \
    apt-get clean && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    ln -s ${WILDFLY_HOME}/standalone/data/addins ${ENTRY_WILDFLY_ADDINS} && \
    chown ${USER}:${USER} -R ${HOME} ${ENTRY_LOGS} ${ENTRY_WILDFLY_ADDINS} ${ENTRY_WILDFLY_LOGS} ${ENTRY_USAGE} && \
    chmod 777 -R ${HOME} ${ENTRY_LOGS} ${ENTRY_WILDFLY_LOGS} && \
    rm -rf ${MOS_TEMP_PATH}/* /var/lib/apt/lists/* /var/cache/apt/*

USER ${USER}

# ports
EXPOSE 8009 8080 9990 8443 9993 8787
