ARG TAG=mosaicgreifswald/zulujre:21
FROM ${TAG}

# ###license-information-start###
# The MOSAIC-Project - WildFly with MySQL-Connector and Healthcheck
# __
# Copyright (C) 2009 - 2025 Institute for Community Medicine
# University Medicine of Greifswald - mosaic-project@uni-greifswald.de
# __
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ###license-information-end###

# variables
ARG DATE_YMD="20250109"
ARG MAVEN_REPOSITORY="https://repo1.maven.org/maven2"

ARG WILDFLY_VERSION="34.0.1.Final"
ARG WILDFLY_DOWNLOAD_URL="https://github.com/wildfly/wildfly/releases/download/${WILDFLY_VERSION}/wildfly-${WILDFLY_VERSION}.tar.gz"
ARG WILDFLY_SHA256="696a39f46c02ce428b9ceb699260d360514f7e6a920e80ed33e4390bf27d0d2a"

ARG MYSQL_CONNECTOR_VERSION="9.1.0"
ARG MYSQL_CONNECTOR_DOWNLOAD_URL="https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-${MYSQL_CONNECTOR_VERSION}.tar.gz"
ARG MYSQL_CONNECTOR_SHA256="8776e2ebc46072c9a47ea59d98298c4273bd9f16a7b26b5dfa4744535aa26c62"

ARG ECLIPSELINK_VERSION="4.0.5"
ARG ECLIPSELINK_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/eclipse/persistence/eclipselink/${ECLIPSELINK_VERSION}/eclipselink-${ECLIPSELINK_VERSION}.jar"
ARG ECLIPSELINK_PATH="modules/system/layers/base/org/eclipse/persistence/main"
ARG ECLIPSELINK_SHA256="753083822643b11e8c320a00853d8ae3ae25746d49c9621a86dd964fb6ff7344"

ENV WILDFLY_HOME="${HOME}/wildfly" \
    JBOSS_CLI="${HOME}/wildfly/bin/jboss-cli.sh" \
    LAUNCH_JBOSS_IN_BACKGROUND="true" \
    LOG4J_FORMAT_MSG_NO_LOOKUPS="true" \
	\
	ENTRY_WILDFLY_CLI="/entrypoint-wildfly-cli" \
	ENTRY_WILDFLY_DEPLOYS="/entrypoint-wildfly-deployments" \
	ENTRY_WILDFLY_ADDINS="/entrypoint-wildfly-addins" \
	ENTRY_WILDFLY_LOGS="/entrypoint-wildfly-logs" \
	ENTRY_WILDFLY_SERVER_KEYSTORE="/entrypoint-wildfly-server-keystore" \
	\
    WF_MARKERFILES="auto" \
    WF_ADMIN_USER="admin" \
    WF_DEBUG="false" \
    DEBUG_PORT="*:8787" \
    JAVA_OPTS="-server -Xms1G -Xmx6G -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman" \
	WF_MAX_PARAMETERS="100000" \
	WF_ENABLE_HTTP2="FALSE"

# annotations
LABEL org.opencontainers.image.authors="ronny.schuldt@uni-greifswald.de" \
      org.opencontainers.image.source="https://hub.docker.com/repository/docker/mosaicgreifswald/wildfly" \
      org.opencontainers.image.version="34-${DATE_YMD}" \
      org.opencontainers.image.vendor="uni-greifswald.de" \
      org.opencontainers.image.title="mosaic-wildfly" \
      org.opencontainers.image.license="AGPLv3" \
      org.opencontainers.image.description="This is a Docker image for the Java application server WildFly. The image is based on slim debian-image and prepared for the tools of the university medicine greifswald (but can also be used for other similar projects)."

# create folders and permissions
USER root
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["scripts", "${WILDFLY_HOME}"]
COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["help-and-usage", "${ENTRY_USAGE}/"]
RUN cd ${MOS_TEMP_PATH} && \
    echo "> 1. install system-updates" && \
    if [ "$(date +%F)" != "$(cat /var/log/apt/history.log | grep 'Date:' | tail -n1 | cut -d' ' -f2)" ]; then \
		apt-get update && apt-get upgrade -y; register --os-updated; \
	fi && \
    \
    echo "> 2. create folders and permissions" && \
    mkdir -m 777 ${ENTRY_WILDFLY_CLI} ${ENTRY_WILDFLY_DEPLOYS} ${ENTRY_LOGS}/wildfly && \
    chown ${USER}:${USER} -R ${ENTRY_WILDFLY_CLI} ${ENTRY_WILDFLY_DEPLOYS} ${ENTRY_LOGS}/wildfly && \
    ln -s ${ENTRY_LOGS}/wildfly ${ENTRY_WILDFLY_LOGS} && \
    \
    echo "> 3. install wildfly" && \
    (curl -Lfo wildfly.tar.gz ${WILDFLY_DOWNLOAD_URL} || (>&2 /bin/echo -e "\ncurl -Lso wildfly.tar.gz ${WILDFLY_DOWNLOAD_URL}\n" && exit 1))  && \
    (sha256sum wildfly.tar.gz | grep -q ${WILDFLY_SHA256} || (>&2 echo "sha256sum failed $(sha256sum wildfly.tar.gz)" && exit 1)) && \
    tar xf wildfly.tar.gz && \
    cp -R wildfly-${WILDFLY_VERSION}/* ${WILDFLY_HOME}/ && \
    rm -rf ${WILDFLY_HOME}/bin/*.bat ${WILDFLY_HOME}/bin/*.ps1 ${WILDFLY_HOME}/docs && \
    mkdir -pm 777 ${WILDFLY_HOME}/standalone/log && touch ${WILDFLY_HOME}/standalone/log/server.log && \
    \
    echo "> 4. get mysql-connector " && \
    (curl -Lfo mysql-connector-java.tar.gz ${MYSQL_CONNECTOR_DOWNLOAD_URL} || (>&2 /bin/echo -e "\ncurl -Lfo mysql-connector-java.tar.gz ${MYSQL_CONNECTOR_DOWNLOAD_URL}\n" && exit 1))  && \
    tar xf mysql-connector-java.tar.gz && \
    mv mysql-connector-j-*/mysql*jar ./mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar && \
    (sha256sum mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar | grep -q ${MYSQL_CONNECTOR_SHA256} || (>&2 echo "sha256sum failed $(sha256sum mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar)" && exit 1)) && \
    \
    echo "> 5. get eclipselink " && \
    (curl -Lfo ${WILDFLY_HOME}/${ECLIPSELINK_PATH}/eclipselink-${ECLIPSELINK_VERSION}.jar ${ECLIPSELINK_DOWNLOAD_URL} || (>&2 /bin/echo -e "\ncurl -Lfo ${WILDFLY_HOME}/${ECLIPSELINK_PATH}/eclipselink-${ECLIPSELINK_VERSION}.jar ${ECLIPSELINK_DOWNLOAD_URL}\n" && exit 1))  && \
    (sha256sum ${WILDFLY_HOME}/${ECLIPSELINK_PATH}/eclipselink-${ECLIPSELINK_VERSION}.jar | grep -q ${ECLIPSELINK_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${WILDFLY_HOME}/${ECLIPSELINK_PATH}/eclipselink-${ECLIPSELINK_VERSION}.jar)" && exit 1)) && \
    sed -i "s/<\/resources>/    <resource-root path=\"eclipselink-${ECLIPSELINK_VERSION}.jar\"\/>\n    <\/resources>/;\
        s/<\/dependencies>/    <module name=\"java.rmi\"\/>\n        <module name=\"java.desktop\"\/>\n        <module name=\"java.xml\"\/>\n    <\/dependencies>/" ${WILDFLY_HOME}/${ECLIPSELINK_PATH}/module.xml && \
    chown -R ${USER}:${USER} ${WILDFLY_HOME}/${ECLIPSELINK_PATH} && \
    \
    echo "> 6. prepare wildfly" && \
    (${WILDFLY_HOME}/bin/standalone.sh &) && \
    START=$(date +%s) && \
    TIMEOUT=30 && \
    (until `/bin/bash ${WILDFLY_HOME}/wildfly_started.sh`;do sleep 1;SEC=$(($(date +%s)-START));if [ ${SEC} -ge $TIMEOUT ];then exit 1;fi;done) && \
    ($JBOSS_CLI --connect --commands=" \
    	module add --name=com.mysql --resources=${MOS_TEMP_PATH}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar --dependencies=javax.api\,javax.transaction.api, \
    	/subsystem=datasources/jdbc-driver=mysql:add(driver-name=mysql,driver-module-name=com.mysql,driver-class-name=com.mysql.cj.jdbc.Driver), \
    	/subsystem=deployment-scanner/scanner=default:write-attribute(name=scan-enabled,value=false), \
    	/subsystem=deployment-scanner/scanner=entrypoint:add(scan-interval=5000,path=${ENTRY_WILDFLY_DEPLOYS}), \
    	/extension=org.wildfly.extension.microprofile.health-smallrye:add, \
    	/subsystem=microprofile-health-smallrye:add, \
    	/subsystem=undertow/server=default-server/ajp-listener=myListener:add(socket-binding=ajp, scheme=http, enabled=true), \
    	/subsystem=elytron/file-audit-log=local-audit:remove(), \
    	/subsystem=logging/pattern-formatter=NO_DATE_DETAILED:add(pattern=\"%d{HH:mm:ss,SSS} %-5p %-4L [%c] (%t) %s%E%n\"), \
    	/subsystem=logging/pattern-formatter=NO_DATE_COMPACT:add(pattern=\"%d{HH:mm:ss,SSS} %-5.5p %-4.4L %-40.40c{2.} | %m%n\"), \
    	:shutdown" || exit 1) && \
    echo -n "true" > ${MOS_READY_PATH}/markerfiles_mode && \
    \
    echo "> 7. register wildfly" && \
    register \
      --add-version="WildFly:${WILDFLY_VERSION}" \
      --add-version="MySQL-Connector:${MYSQL_CONNECTOR_VERSION}" \
      --add-version="EclipseLink:\$(ls ${WILDFLY_HOME}/${ECLIPSELINK_PATH}/eclipselink-* | sed -r 's/^.+-([0-9\.]+)\.jar$/\1/' | cat)" \
      --add-entrypoint="ENTRY_WILDFLY_CLI:${ENTRY_WILDFLY_CLI}" \
      --add-entrypoint="ENTRY_WILDFLY_DEPLOYS:${ENTRY_WILDFLY_DEPLOYS}" \
      --add-entrypoint="ENTRY_WILDFLY_ADDINS:${ENTRY_WILDFLY_ADDINS}" \
      --add-entrypoint="ENTRY_WILDFLY_LOGS:${ENTRY_WILDFLY_LOGS}" \
      --add-entrypoint="ENTRY_WILDFLY_SERVER_KEYSTORE:${ENTRY_WILDFLY_SERVER_KEYSTORE}" \
      --add-healthcheck-script="${WILDFLY_HOME}/healthcheck_wildfly.sh" \
      --add-run-script="20:service:${WILDFLY_HOME}/run_wildfly.sh:${WILDFLY_HOME}/wildfly_started.sh" && \
    \
    echo "> 8. cleanup" && \
    apt-get clean && \
    apt-get autoclean && \
    apt-get autoremove && \
    mkdir -pm 777 ${WILDFLY_HOME}/standalone/data/addins && \
    ln -s ${WILDFLY_HOME}/standalone/data/addins ${ENTRY_WILDFLY_ADDINS} && \
    chown ${USER}:${USER} -R ${HOME} ${ENTRY_LOGS} ${ENTRY_WILDFLY_ADDINS} ${ENTRY_WILDFLY_LOGS} ${ENTRY_USAGE} && \
    chmod 777 -R ${WILDFLY_HOME}/domain/configuration && \
    chmod 777 -R ${HOME} ${ENTRY_LOGS} ${ENTRY_WILDFLY_LOGS} ${ENTRY_USAGE} && \
	chmod 555 -R ${WILDFLY_HOME}/*.sh ${WILDFLY_HOME}/**/*.sh && \
    rm -rf ${MOS_TEMP_PATH}/* ${WILDFLY_HOME}/standalone/configuration/standalone_xml_history/current/* ${WILDFLY_HOME}/standalone/log/* /var/lib/apt/lists/* /var/cache/apt/*

USER ${USER}

# ports
EXPOSE 8009 8080 9990 8443 9993 8787
