name: Build and push wildfly-image

on:
  push:
    branches:
      - main
    paths:
      - 'image/wildfly/**'
      - '.github/workflows/docker-wildfly.yml'

  workflow_run:
    workflows:
      - Build and push zulujre-image
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker

    if: >
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Get WildFly version
        id: wildfly
        shell: bash
        run: |
          set -euo pipefail
      
          fullversion=$(grep -E '^ARG WILDFLY_VERSION=' image/wildfly/Dockerfile.wildfly.40 \
            | sed -E 's/^ARG WILDFLY_VERSION="?([0-9\.]+)\..*$"?/\1/' \
            | head -n1)
          majorversion="${fullversion%%.*}"

          echo "WildFly full version: ${fullversion}"
          echo "WildFly major version: ${majorversion}"

          echo "fullversion=${fullversion}" >> "$GITHUB_OUTPUT"
          echo "majorversion=${majorversion}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./image/wildfly
          file: ./image/wildfly/Dockerfile.wildfly.40
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wildfly:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wildfly:${{ steps.wildfly.outputs.fullversion }}
            ${{ secrets.DOCKERHUB_USERNAME }}/wildfly:${{ steps.wildfly.outputs.majorversion }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
